# Маппинг тут происходит следующим образом: хост:контейнер
version: "3"
services:
  mysoundauth:
    container_name: mysound_auth
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssql
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: mysound_auth_mssql
    environment:
      SA_PASSWORD: "Qwertyuiop12345678"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  proxy:
    image: nginx:latest
    restart: always
    container_name: mysound_auth_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 81:80
